"""empty message

Revision ID: 39e8dd6e3710
Revises: 3e760cc0a2ae
Create Date: 2019-06-24 11:25:43.780646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e8dd6e3710'
down_revision = '3e760cc0a2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('add_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('add_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'add_time')
    op.drop_column('articles', 'add_time')
    # ### end Alembic commands ###
