"""empty message

Revision ID: 3effd16d6f6a
Revises: 95d046d9b74b
Create Date: 2019-06-24 16:28:40.279666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3effd16d6f6a'
down_revision = '95d046d9b74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('openid', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'user', ['openid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'openid')
    # ### end Alembic commands ###
