"""empty message

Revision ID: 8ae0ca455305
Revises: 3045f83c2950
Create Date: 2019-06-24 16:39:38.215083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae0ca455305'
down_revision = '3045f83c2950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group', sa.Integer(), nullable=True, comment={(1, '1队'), (3, '3队'), (2, '2队')}))
    op.create_unique_constraint(None, 'user', ['group'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'group')
    # ### end Alembic commands ###
