"""empty message

Revision ID: a05765ed3a4c
Revises: ca0e9ac811a5
Create Date: 2019-06-22 23:53:57.328836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05765ed3a4c'
down_revision = 'ca0e9ac811a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('add_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'add_time')
    # ### end Alembic commands ###
