"""empty message

Revision ID: a3e8e3b1246e
Revises: 07592440ba2f
Create Date: 2019-06-24 11:01:56.736906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3e8e3b1246e'
down_revision = '07592440ba2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'add_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('add_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
