"""empty message

Revision ID: b312a39b2732
Revises: 35421d79ad22
Create Date: 2019-06-24 15:11:23.628323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b312a39b2732'
down_revision = '35421d79ad22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nickname', table_name='user')
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', mysql.VARCHAR(length=20), nullable=True))
    op.create_index('nickname', 'user', ['nickname'], unique=True)
    # ### end Alembic commands ###
