"""empty message

Revision ID: b34096dda151
Revises: 3effd16d6f6a
Create Date: 2019-06-24 16:32:36.232552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b34096dda151'
down_revision = '3effd16d6f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'work')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('work', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
